import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { ConvexClientProvider } from "@/providers/convexClientProvider";
import { Toaster } from "@/components/ui/sonner"
import StoreProvider from "@/providers/StoreProvider";
import RenameModal from "@/components/modals/RenameModal";
import ModalProvider from "@/providers/ModalProvider";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <ConvexClientProvider>
          <StoreProvider>
            <Toaster />
            <ModalProvider />
            {children}
          </StoreProvider>
        </ConvexClientProvider>

      </body>
    </html>
  );
}
